org: creativogee
app: project-hilda
service: ${self:app}-http-api
frameworkVersion: '3'
custom:
  APP_NAME: ${self:app}-${sls:stage}
  SERVICE_NAME: ${self:service}-${sls:stage}
  BUCKET_NAME: sagemaker-${self:app}

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors:
      allowedOrigins:
        - 'https://develop.d1d66d68ewa2dw.amplifyapp.com'
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Api-Key
        - Access-Control-Allow-Origin
        - Access-Control-Allow-Headers
        - Access-Control-Allow-Methods
        - Access-Control-Allow-Credentials
      allowedMethods:
        - GET
        - POST
        - PUT
        - OPTIONS

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.APP_NAME}-organizations
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.APP_NAME}-billings
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:PutObjectAcl
          Resource: arn:aws:s3:::${self:custom.BUCKET_NAME}/*

  environment:
    APP_NAME: ${self:custom.APP_NAME}
    SERVICE_NAME: ${self:custom.SERVICE_NAME}
    BUCKET_NAME: ${self:custom.BUCKET_NAME}

functions:
  updateProfile:
    handler: handlers/updateProfile.handler
    events:
      - httpApi:
          path: /profile
          method: post

  getProfile:
    handler: handlers/getProfile.handler
    events:
      - httpApi:
          path: /profile
          method: get

  onboarding:
    handler: handlers/onboarding.handler
    events:
      - httpApi:
          path: /onboarding
          method: post

  getPresignedURL:
    handler: handlers/getPresignedURL.handler
    events:
      - httpApi:
          path: /presigned-url
          method: get

  login:
    handler: handlers/login.handler
    events:
      - httpApi:
          path: /login
          method: post

  getAccessKey:
    handler: handlers/getAccessKey.handler
    events:
      - httpApi:
          path: /access-key
          method: get
